### ISSUE TITLE
Possible duplication of effort

### ISSUE THREAD

**Issue by gep13** [moongdev/Cake.CMakeBuild#1]
@moongdev I wanted to reach out to speak to you about the work that you are doing here.  Is there a reason that you decided to fork the existing Cake.CMake addin, rather than contributing to the existing one?

If you are interested, I can provide you with permissions to that existing repository, rather than having you do similar work here.

Personally, I think this is a much better solution, than diluting the Cake eco-system with duplicate addins.

What do you think?

Please let me know if you have any questions.

**Comment by moongdev** [comment]
Hello @gep13 the main reason that I see that PR's are not reviewed a lot of time and nobody working on this project. For my internal(home) project I use combine of c# and c++ project and I need a new features for a build c++ projects by one line. I'll be a happy to improve the existing library and do not make duplicates. 
My questions here:
1. Somebody actively works on this addin? 
2. How I can join to work on addin?

Thanks!

**Comment by gep13** [comment]
Part of the reason that we encourage addin authors/maintainers to move their addin's into the Cake-Contrib Organisation is to account for people "coming and going".  i.e. sometimes people don't have time to work on things, but by having the addin's in a common Organisation, we can add  additional maintainers when required.

So, to answer your question, no I don't believe there is anyone actively working on the Cake.CMake addin, but I can certainly add you to the Organisation with admin rights to the repository, so that you can begin working on it.

What do you think?  Is this something that you would like to help with?

**Comment by moongdev** [comment]
I not against and yes I exactly meant it. Have you a code standards for addins?

**Comment by gep13** [comment]
@moongdev That is great news!  I will send you an invite to the repository just now.  Setting up permissions for AppVeyor (which is where we run our CI Builds) will take longer, so I will do that tomorrow.

In terms of code standards, there are no strict rules in place, no.  There are some guidelines for various things here:

https://github.com/cake-contrib/Home/blob/master/Guidelines.md

**Comment by gep13** [comment]
@moongdev I have just sent you an invite to join the Organisation, and I have given you access to the Cake.CMake repository.

Do you use Twitter and Slack?  If so, can you let me know your details?  Twitter is just used for general communication, but we use Slack for Cake-Contrib Maintainers, and it is a place to ask any questions that you might have about anything.

**Comment by moongdev** [comment]
You can add me as Twitter: @denis_moong and Slack by email tranquilfirst@gmail.com

**Comment by gep13** [comment]
@moongdev thanks!  I have sent you an invite to the Slack Team, and I have followed your Twitter user from the cake-contrib Twitter account.

Do you think you will be in a position to continue development on the Cake.CMake repository, rather than on this repository?

I will go ahead and close this issue.  Please let me know if you have any questions on Slack.
